In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving result.xlsx to result.xlsx

In [3]:
import io
result = pd.read_excel(io.BytesIO(uploaded['result.xlsx']))

In [4]:
result

   regno     name college branch  semester  sub1  sub2  sub3
0      1    raghu      rv    csc         7  80.0  90.0  65.0
1      2    vidya      rv    csc         7  85.0  95.0  78.0
2      3    ranga   pesit    csc         7  90.0  98.0  80.0
3      4    rohan   pesit    csc         7  94.0  99.0  85.0
4      5    ganga   bmsit    csc         7  97.0  88.0  89.0
5      6   babita   msrit    ece         7  97.0  86.0   NaN
6      7  gautami   msrit    ece         7  97.0  86.0  90.0
7      8     arun   msrit    csc         7   NaN  86.0  90.0
8      9     arun   msrit    csc         7  86.0   NaN  90.0

In [5]:
result['total'] = result['sub1']+result['sub2']+result['sub3']
result.head()

   regno   name college branch  semester  sub1  sub2  sub3  total
0      1  raghu      rv    csc         7  80.0  90.0  65.0  235.0
1      2  vidya      rv    csc         7  85.0  95.0  78.0  258.0
2      3  ranga   pesit    csc         7  90.0  98.0  80.0  268.0
3      4  rohan   pesit    csc         7  94.0  99.0  85.0  278.0
4      5  ganga   bmsit    csc         7  97.0  88.0  89.0  274.0

In [7]:
result['avg']=result['total']/3
result.head()

   regno   name college branch  semester  sub1  sub2  sub3  total        avg
0      1  raghu      rv    csc         7  80.0  90.0  65.0  235.0  78.333333
1      2  vidya      rv    csc         7  85.0  95.0  78.0  258.0  86.000000
2      3  ranga   pesit    csc         7  90.0  98.0  80.0  268.0  89.333333
3      4  rohan   pesit    csc         7  94.0  99.0  85.0  278.0  92.666667
4      5  ganga   bmsit    csc         7  97.0  88.0  89.0  274.0  91.333333

In [10]:
result['sub1'].fillna(value=(result['sub2']+result['sub3'])/2, inplace = True)
result['sub2'].fillna(value=(result['sub1']+result['sub3'])/2, inplace = True)
result['sub3'].fillna(value=(result['sub2']+result['sub1'])/2, inplace = True)
result['total'].fillna(value=(result['sub1']+result['sub2']+result['sub1']), inplace = True)
result['avg'].fillna(value=(result['sub1']+result['sub2']+result['sub1'])/3, inplace = True)
result

   regno     name college branch  semester  sub1  sub2  sub3  total        avg
0      1    raghu      rv    csc         7  80.0  90.0  65.0  235.0  78.333333
1      2    vidya      rv    csc         7  85.0  95.0  78.0  258.0  86.000000
2      3    ranga   pesit    csc         7  90.0  98.0  80.0  268.0  89.333333
3      4    rohan   pesit    csc         7  94.0  99.0  85.0  278.0  92.666667
4      5    ganga   bmsit    csc         7  97.0  88.0  89.0  274.0  91.333333
5      6   babita   msrit    ece         7  97.0  86.0  91.5  280.0  93.333333
6      7  gautami   msrit    ece         7  97.0  86.0  90.0  273.0  91.000000
7      8     arun   msrit    csc         7  88.0  86.0  90.0  262.0  87.333333
8      9     arun   msrit    csc         7  86.0  88.0  90.0  260.0  86.666667

In [20]:
result[result['total'] == result['total'].max()]

   regno    name college branch  semester  sub1  sub2  sub3  total        avg
5      6  babita   msrit    ece         7  97.0  86.0  91.5  280.0  93.333333

In [21]:
result[result['sub1'] == result['sub1'].max()]

   regno     name college branch  semester  sub1  sub2  sub3  total        avg
4      5    ganga   bmsit    csc         7  97.0  88.0  89.0  274.0  91.333333
5      6   babita   msrit    ece         7  97.0  86.0  91.5  280.0  93.333333
6      7  gautami   msrit    ece         7  97.0  86.0  90.0  273.0  91.000000

In [22]:
result[result['sub2'] == result['sub2'].max()]

   regno   name college branch  semester  sub1  sub2  sub3  total        avg
3      4  rohan   pesit    csc         7  94.0  99.0  85.0  278.0  92.666667

In [23]:
result[result['sub3'] == result['sub3'].max()]

   regno    name college branch  semester  sub1  sub2  sub3  total        avg
5      6  babita   msrit    ece         7  97.0  86.0  91.5  280.0  93.333333

In [24]:
result.drop_duplicates(keep="first")

   regno     name college branch  semester  sub1  sub2  sub3  total        avg
0      1    raghu      rv    csc         7  80.0  90.0  65.0  235.0  78.333333
1      2    vidya      rv    csc         7  85.0  95.0  78.0  258.0  86.000000
2      3    ranga   pesit    csc         7  90.0  98.0  80.0  268.0  89.333333
3      4    rohan   pesit    csc         7  94.0  99.0  85.0  278.0  92.666667
4      5    ganga   bmsit    csc         7  97.0  88.0  89.0  274.0  91.333333
5      6   babita   msrit    ece         7  97.0  86.0  91.5  280.0  93.333333
6      7  gautami   msrit    ece         7  97.0  86.0  90.0  273.0  91.000000
7      8     arun   msrit    csc         7  88.0  86.0  90.0  262.0  87.333333
8      9     arun   msrit    csc         7  86.0  88.0  90.0  260.0  86.666667