In [ ]:
import pandas as pd
import numpy as np

from google.colab import files

*   List item
*   List item


uploaded = files.upload()

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import io
iris = pd.read_csv(io.BytesIO(uploaded['iris.csv']))

In [ ]:
iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris["setosa"] = iris.Species.map({"setosa" : 1,"versicolor":0, "virginica" : 0})
iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  setosa
0           5.1          3.5           1.4          0.2  setosa       1
1           4.9          3.0           1.4          0.2  setosa       1
2           4.7          3.2           1.3          0.2  setosa       1
3           4.6          3.1           1.5          0.2  setosa       1
4           5.0          3.6           1.4          0.2  setosa       1

In [ ]:
pd.get_dummies(iris.Species,prefix = "Species")

     Species_setosa  Species_versicolor  Species_virginica
0                 1                   0                  0
1                 1                   0                  0
2                 1                   0                  0
3                 1                   0                  0
4                 1                   0                  0
..              ...                 ...                ...
145               0                   0                  1
146               0                   0                  1
147               0                   0                  1
148               0                   0                  1
149               0                   0                  1

[150 rows x 3 columns]

In [ ]:
pd.get_dummies(iris.Species,prefix = "Species").iloc[:,0:1]

     Species_setosa
0                 1
1                 1
2                 1
3                 1
4                 1
..              ...
145               0
146               0
147               0
148               0
149               0

[150 rows x 1 columns]

In [ ]:
species_dummies = pd.get_dummies(iris.Species,prefix = "Species").iloc[:,0:]

In [ ]:
iris = pd.concat([iris,species_dummies],axis = 1)
iris.head()

   Sepal.Length  Sepal.Width  ...  Species_versicolor  Species_virginica
0           5.1          3.5  ...                   0                  0
1           4.9          3.0  ...                   0                  0
2           4.7          3.2  ...                   0                  0
3           4.6          3.1  ...                   0                  0
4           5.0          3.6  ...                   0                  0

[5 rows x 9 columns]

In [ ]:
pd.get_dummies(iris,columns = ["Species"],drop_first = True).head()

   Sepal.Length  Sepal.Width  ...  Species_versicolor  Species_virginica
0           5.1          3.5  ...                   0                  0
1           4.9          3.0  ...                   0                  0
2           4.7          3.2  ...                   0                  0
3           4.6          3.1  ...                   0                  0
4           5.0          3.6  ...                   0                  0

[5 rows x 10 columns]

In [ ]:
iris.rank()

     Sepal.Length  Sepal.Width  ...  Species_versicolor  Species_virginica
0            37.0        128.5  ...                50.5               50.5
1            19.5         70.5  ...                50.5               50.5
2            10.5        101.0  ...                50.5               50.5
3             7.5         89.0  ...                50.5               50.5
4            27.5        133.5  ...                50.5               50.5
..            ...          ...  ...                 ...                ...
145         126.5         70.5  ...                50.5              125.5
146         104.0         15.5  ...                50.5              125.5
147         118.0         70.5  ...                50.5              125.5
148          97.5        119.5  ...                50.5              125.5
149          82.0         70.5  ...                50.5              125.5

[150 rows x 9 columns]

In [ ]:
iris['Rank2'] = iris['Sepal.Length'].groupby(iris["Species"]).rank(ascending=1)
iris.head()

   Sepal.Length  Sepal.Width  ...  Species_virginica  Rank2
0           5.1          3.5  ...                  0   32.5
1           4.9          3.0  ...                  0   18.5
2           4.7          3.2  ...                  0   10.5
3           4.6          3.1  ...                  0    7.5
4           5.0          3.6  ...                  0   24.5

[5 rows x 10 columns]

In [ ]:
iris['cum_sum'] = iris["Sepal.Length"].cumsum()
iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  ...  Species_virginica Rank2  cum_sum
0           5.1          3.5           1.4  ...                  0  32.5      5.1
1           4.9          3.0           1.4  ...                  0  18.5     10.0
2           4.7          3.2           1.3  ...                  0  10.5     14.7
3           4.6          3.1           1.5  ...                  0   7.5     19.3
4           5.0          3.6           1.4  ...                  0  24.5     24.3

[5 rows x 11 columns]

In [ ]:
iris["cumsum2"] = iris.groupby(["Species"])["Sepal.Length"].cumsum()
iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  ...  Rank2 cum_sum  cumsum2
0           5.1          3.5           1.4  ...   32.5     5.1      5.1
1           4.9          3.0           1.4  ...   18.5    10.0     10.0
2           4.7          3.2           1.3  ...   10.5    14.7     14.7
3           4.6          3.1           1.5  ...    7.5    19.3     19.3
4           5.0          3.6           1.4  ...   24.5    24.3     24.3

[5 rows x 12 columns]