# Imports

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

# IO

In [ ]:
import io
income = pd.read_csv('income.csv')

In [ ]:
income

   Index                 State    Y2002  ...    Y2013    Y2014    Y2015
0      A               Alabama  1296530  ...  1852841  1558906  1916661
1      A                Alaska  1170302  ...  1985302  1580394  1979143
2      A               Arizona  1742027  ...  1363279  1525866  1647724
3      A              Arkansas  1485531  ...  1591896  1360959  1329341
4      C            California  1685349  ...  1156536  1388461  1644607
5      C              Colorado  1343824  ...  1178355  1383978  1330736
6      C           Connecticut  1610512  ...  1582249  1503156  1718072
7      D              Delaware  1330403  ...  1671279  1803169  1627508
8      D  District of Columbia  1111437  ...  1912654  1782169  1410183
9      F               Florida  1964626  ...  1107448  1407784  1170389
10     G               Georgia  1929009  ...  1887157  1259353  1725470
11     H                Hawaii  1461570  ...  1517184  1948108  1150882
12     I                 Idaho  1353210  ...  1312561  1713718  1757171
13     I              Illinois  1508356  ...  1915435  1645465  1583516
14     I               Indiana  1776918  ...  1129794  1988394  1467614
15     I                  Iowa  1499269  ...  1173694  1431705  1641866
16     K                Kansas  1509054  ...  1410249  1930090  1385528
17     K              Kentucky  1813878  ...  1878271  1722762  1913350
18     L             Louisiana  1584734  ...  1287663  1908602  1403857
19     M                 Maine  1582720  ...  1318546  1116792  1529233
20     M              Maryland  1579713  ...  1314343  1979529  1569566
21     M         Massachusetts  1647582  ...  1731917  1669749  1963337
22     M              Michigan  1295635  ...  1815596  1965196  1646634
23     M             Minnesota  1729921  ...  1972021  1515366  1864553
24     M           Mississippi  1983285  ...  1907777  1649668  1991232
25     M              Missouri  1221316  ...  1698105  1767835  1996005
26     M               Montana  1877154  ...  1465705  1110394  1125903
27     N              Nebraska  1885081  ...  1690920  1459243  1802211
28     N                Nevada  1426117  ...  1283813  1225348  1903804
29     N         New Hampshire  1419776  ...  1197576  1242623  1963313
30     N            New Jersey  1605532  ...  1100990  1850165  1183568
31     N            New Mexico  1819239  ...  1623388  1533494  1868612
32     N              New York  1395149  ...  1718837  1619033  1367705
33     N        North Carolina  1616742  ...  1104893  1596452  1229085
34     N          North Dakota  1618807  ...  1529024  1563898  1604118
35     O                  Ohio  1802132  ...  1840898  1880804  1573117
36     O              Oklahoma  1173918  ...  1900523  1956742  1307678
37     O                Oregon  1794912  ...  1522129  1509171  1893515
38     P          Pennsylvania  1320191  ...  1475344  1931500  1668232
39     R          Rhode Island  1501744  ...  1531212  1990412  1611730
40     S        South Carolina  1631522  ...  1591735  1188417  1110655
41     S          South Dakota  1159037  ...  1147488  1302834  1136443
42     T             Tennessee  1811867  ...  1560887  1349173  1162164
43     T                 Texas  1520591  ...  1698698  1646508  1705322
44     U                  Utah  1771096  ...  1123353  1801019  1729273
45     V               Vermont  1146902  ...  1146278  1282790  1565924
46     V              Virginia  1134317  ...  1647032  1706707  1850394
47     W            Washington  1977749  ...  1273834  1387428  1377341
48     W         West Virginia  1677347  ...  1683127  1204344  1198791
49     W             Wisconsin  1788920  ...  1510119  1701650  1846238
50     W               Wyoming  1775190  ...  1994022  1204029  1853858

[51 rows x 16 columns]

#BASICS

In [ ]:
income.columns

Index(['Index', 'State', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007',
       'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015'],
      dtype='object')

In [ ]:
income.columns[0:2]

Index(['Index', 'State'], dtype='object')

In [ ]:
income.shape

(51, 16)

In [ ]:
print(income.shape[0],income.shape[1])

51 16

In [ ]:
print(income.head())
print(income.head(2))  #shows first 2 rows.
print(income.tail()) 
print(income.tail(2))  #shows last 2 rows

  Index       State    Y2002    Y2003  ...    Y2012    Y2013    Y2014    Y2015
0     A     Alabama  1296530  1317711  ...  1186741  1852841  1558906  1916661
1     A      Alaska  1170302  1960378  ...  1512804  1985302  1580394  1979143
2     A     Arizona  1742027  1968140  ...  1907284  1363279  1525866  1647724
3     A    Arkansas  1485531  1994927  ...  1216675  1591896  1360959  1329341
4     C  California  1685349  1675807  ...  1921845  1156536  1388461  1644607

[5 rows x 16 columns]
  Index    State    Y2002    Y2003  ...    Y2012    Y2013    Y2014    Y2015
0     A  Alabama  1296530  1317711  ...  1186741  1852841  1558906  1916661
1     A   Alaska  1170302  1960378  ...  1512804  1985302  1580394  1979143

[2 rows x 16 columns]
   Index          State    Y2002    Y2003  ...    Y2012    Y2013    Y2014    Y2015
46     V       Virginia  1134317  1163996  ...  1262342  1647032  1706707  1850394
47     W     Washington  1977749  1687136  ...  1775787  1273834  1387428  1377341
48     W  West Virginia  1677347  1380662  ...  1462137  1683127  1204344  1198791
49     W      Wisconsin  1788920  1518578  ...  1729177  1510119  1701650  1846238
50     W        Wyoming  1775190  1498098  ...  1673668  1994022  1204029  1853858

[5 rows x 16 columns]
   Index      State    Y2002    Y2003  ...    Y2012    Y2013    Y2014    Y2015
49     W  Wisconsin  1788920  1518578  ...  1729177  1510119  1701650  1846238
50     W    Wyoming  1775190  1498098  ...  1673668  1994022  1204029  1853858

[2 rows x 16 columns]

# Series

In [ ]:
s = pd.Series([1,2,3,1,2], dtype="category")
s

0    1
1    2
2    3
3    1
4    2
dtype: category
Categories (3, int64): [1, 2, 3]

# Unique

In [ ]:
income.Index.unique()

array(['A', 'C', 'D', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P',
       'R', 'S', 'T', 'U', 'V', 'W'], dtype=object)

In [ ]:
income.Index.nunique()

19

# Value Counts

In [ ]:
income.Index.value_counts(ascending = True)

H    1
L    1
P    1
F    1
U    1
R    1
G    1
T    2
K    2
S    2
V    2
D    2
O    3
C    3
W    4
I    4
A    4
N    8
M    8
Name: Index, dtype: int64

#Sample

In [ ]:
income.sample(n = 5)

   Index         State    Y2002    Y2003  ...    Y2012    Y2013    Y2014    Y2015
41     S  South Dakota  1159037  1150689  ...  1811156  1147488  1302834  1136443
13     I      Illinois  1508356  1527440  ...  1696729  1915435  1645465  1583516
35     O          Ohio  1802132  1648498  ...  1227303  1840898  1880804  1573117
25     M      Missouri  1221316  1858368  ...  1800052  1698105  1767835  1996005
19     M         Maine  1582720  1678622  ...  1437088  1318546  1116792  1529233

[5 rows x 16 columns]

In [ ]:
income.sample(frac = 0.1)

   Index           State    Y2002    Y2003  ...    Y2012    Y2013    Y2014    Y2015
44     U            Utah  1771096  1195861  ...  1108281  1123353  1801019  1729273
24     M     Mississippi  1983285  1292558  ...  1988270  1907777  1649668  1991232
16     K          Kansas  1509054  1290700  ...  1882929  1410249  1930090  1385528
12     I           Idaho  1353210  1438538  ...  1643855  1312561  1713718  1757171
40     S  South Carolina  1631522  1803455  ...  1532332  1591735  1188417  1110655

[5 rows x 16 columns]

In [ ]:
print(income["State"])
print(income.State)

In [ ]:
income[["Index","State","Y2008"]]

   Index                 State    Y2008
0      A               Alabama  1945229
1      A                Alaska  1551826
2      A               Arizona  1752886
3      A              Arkansas  1188104
4      C            California  1487315
5      C              Colorado  1875146
6      C           Connecticut  1764457
7      D              Delaware  1762096
8      D  District of Columbia  1193245
9      F               Florida  1756185
10     G               Georgia  1773090
11     H                Hawaii  1919423
12     I                 Idaho  1335481
13     I              Illinois  1871645
14     I               Indiana  1139551
15     I                  Iowa  1317983
16     K                Kansas  1949478
17     K              Kentucky  1301848
18     L             Louisiana  1185085
19     M                 Maine  1295877
20     M              Maryland  1112765
21     M         Massachusetts  1978904
22     M              Michigan  1990431
23     M             Minnesota  1328133
24     M           Mississippi  1428291
25     M              Missouri  1735099
26     M               Montana  1251742
27     N              Nebraska  1140598
28     N                Nevada  1903270
29     N         New Hampshire  1762936
30     N            New Jersey  1568034
31     N            New Mexico  1237704
32     N              New York  1732098
33     N        North Carolina  1267737
34     N          North Dakota  1720352
35     O                  Ohio  1516621
36     O              Oklahoma  1256746
37     O                Oregon  1482786
38     P          Pennsylvania  1274168
39     R          Rhode Island  1151409
40     S        South Carolina  1250499
41     S          South Dakota  1171870
42     T             Tennessee  1826406
43     T                 Texas  1785986
44     U                  Utah  1939284
45     V               Vermont  1123567
46     V              Virginia  1803330
47     W            Washington  1545621
48     W         West Virginia  1238174
49     W             Wisconsin  1980167
50     W               Wyoming  1587602

#loc

In [ ]:
print(income.loc[:,["Index","State","Y2008"]])
print(income.loc[0:2,["Index","State","Y2008"]])  #Selecting rows with Index label 0 to 2 & columns
print(income.loc[:,"Index":"Y2008"])  #Selecting consecutive columns
#In the above command both Index and Y2008 are included.
print(income.iloc[:,0:5])

#df

In [ ]:
import numpy as np
x = pd.DataFrame({"var1" : np.arange(1,20,2)}, index=[9,8,7,6,10, 1, 2, 3, 4, 5])
print(x)

    var1
9      1
8      3
7      5
6      7
10     9
1     11
2     13
3     15
4     17
5     19

In [ ]:
data = pd.DataFrame({"A" : ["John","Mary","Julia","Kenny","Henry"], "B" : ["Libra","Capricorn","Aries","Scorpio","Aquarius"]})

In [ ]:
data.columns = ['Names','Zodiac Signs'];data

   Names Zodiac Signs
0   John        Libra
1   Mary    Capricorn
2  Julia        Aries
3  Kenny      Scorpio
4  Henry     Aquarius

#drop

In [ ]:
x1 = income.drop('Index',axis = 1); 
print(x1)

                   State    Y2002    Y2003  ...    Y2013    Y2014    Y2015
0                Alabama  1296530  1317711  ...  1852841  1558906  1916661
1                 Alaska  1170302  1960378  ...  1985302  1580394  1979143
2                Arizona  1742027  1968140  ...  1363279  1525866  1647724
3               Arkansas  1485531  1994927  ...  1591896  1360959  1329341
4             California  1685349  1675807  ...  1156536  1388461  1644607
5               Colorado  1343824  1878473  ...  1178355  1383978  1330736
6            Connecticut  1610512  1232844  ...  1582249  1503156  1718072
7               Delaware  1330403  1268673  ...  1671279  1803169  1627508
8   District of Columbia  1111437  1993741  ...  1912654  1782169  1410183
9                Florida  1964626  1468852  ...  1107448  1407784  1170389
10               Georgia  1929009  1541565  ...  1887157  1259353  1725470
11                Hawaii  1461570  1200280  ...  1517184  1948108  1150882
12                 Idaho  1353210  1438538  ...  1312561  1713718  1757171
13              Illinois  1508356  1527440  ...  1915435  1645465  1583516
14               Indiana  1776918  1734104  ...  1129794  1988394  1467614
15                  Iowa  1499269  1444576  ...  1173694  1431705  1641866
16                Kansas  1509054  1290700  ...  1410249  1930090  1385528
17              Kentucky  1813878  1448846  ...  1878271  1722762  1913350
18             Louisiana  1584734  1110625  ...  1287663  1908602  1403857
19                 Maine  1582720  1678622  ...  1318546  1116792  1529233
20              Maryland  1579713  1404700  ...  1314343  1979529  1569566
21         Massachusetts  1647582  1686259  ...  1731917  1669749  1963337
22              Michigan  1295635  1149931  ...  1815596  1965196  1646634
23             Minnesota  1729921  1675204  ...  1972021  1515366  1864553
24           Mississippi  1983285  1292558  ...  1907777  1649668  1991232
25              Missouri  1221316  1858368  ...  1698105  1767835  1996005
26               Montana  1877154  1540099  ...  1465705  1110394  1125903
27              Nebraska  1885081  1309769  ...  1690920  1459243  1802211
28                Nevada  1426117  1114500  ...  1283813  1225348  1903804
29         New Hampshire  1419776  1854370  ...  1197576  1242623  1963313
30            New Jersey  1605532  1141514  ...  1100990  1850165  1183568
31            New Mexico  1819239  1226057  ...  1623388  1533494  1868612
32              New York  1395149  1611371  ...  1718837  1619033  1367705
33        North Carolina  1616742  1292223  ...  1104893  1596452  1229085
34          North Dakota  1618807  1510193  ...  1529024  1563898  1604118
35                  Ohio  1802132  1648498  ...  1840898  1880804  1573117
36              Oklahoma  1173918  1334639  ...  1900523  1956742  1307678
37                Oregon  1794912  1726665  ...  1522129  1509171  1893515
38          Pennsylvania  1320191  1446723  ...  1475344  1931500  1668232
39          Rhode Island  1501744  1942942  ...  1531212  1990412  1611730
40        South Carolina  1631522  1803455  ...  1591735  1188417  1110655
41          South Dakota  1159037  1150689  ...  1147488  1302834  1136443
42             Tennessee  1811867  1485909  ...  1560887  1349173  1162164
43                 Texas  1520591  1310777  ...  1698698  1646508  1705322
44                  Utah  1771096  1195861  ...  1123353  1801019  1729273
45               Vermont  1146902  1832249  ...  1146278  1282790  1565924
46              Virginia  1134317  1163996  ...  1647032  1706707  1850394
47            Washington  1977749  1687136  ...  1273834  1387428  1377341
48         West Virginia  1677347  1380662  ...  1683127  1204344  1198791
49             Wisconsin  1788920  1518578  ...  1510119  1701650  1846238
50               Wyoming  1775190  1498098  ...  1994022  1204029  1853858

[51 rows x 15 columns]

In [ ]:
income.sort_values("State",ascending = False)
income.sort_values("State",ascending = False,inplace = True)
income.Y2006.sort_values()
income

In [ ]:
income.sort_values(["Index","Y2002"])

In [ ]:
income["difference"] = income.Y2008-income.Y2009

In [ ]:
income

In [ ]:
income["difference2"] = income.eval("Y2008 - Y2009")
income.head()

   Index          State    Y2002  ...    Y2015  difference  difference2
50     W        Wyoming  1775190  ...  1853858       83147        83147
49     W      Wisconsin  1788920  ...  1846238       78773        78773
48     W  West Virginia  1677347  ...  1198791     -301148      -301148
47     W     Washington  1977749  ...  1377341       -9933        -9933
46     V       Virginia  1134317  ...  1850394      213287       213287

[5 rows x 18 columns]

In [ ]:
data = income.assign(ratio = (income.Y2008 / income.Y2009))
data.head()

#describe

In [ ]:
income.describe().iloc[0:2,:]

              Y2002         Y2003  ...     difference    difference2
count  5.100000e+01  5.100000e+01  ...      51.000000      51.000000
mean   1.566034e+06  1.509193e+06  ... -120121.352941 -120121.352941

[2 rows x 16 columns]

In [ ]:
income.describe(include = ['object'])

       Index    State
count     51       51
unique    19       51
top        M  Wyoming
freq       8        1

#mean,  median, aggergate

In [ ]:
print(income.mean())
print(income.median())
print(income.agg(["mean","median"]))

Y2002          1.566034e+06
Y2003          1.509193e+06
Y2004          1.540555e+06
Y2005          1.522064e+06
Y2006          1.530969e+06
Y2007          1.553219e+06
Y2008          1.538398e+06
Y2009          1.658519e+06
Y2010          1.504108e+06
Y2011          1.574968e+06
Y2012          1.591135e+06
Y2013          1.530078e+06
Y2014          1.583360e+06
Y2015          1.588297e+06
difference    -1.201214e+05
difference2   -1.201214e+05
dtype: float64
Y2002          1584734.0
Y2003          1485909.0
Y2004          1522230.0
Y2005          1480280.0
Y2006          1531641.0
Y2007          1563062.0
Y2008          1545621.0
Y2009          1658551.0
Y2010          1498662.0
Y2011          1575533.0
Y2012          1643855.0
Y2013          1531212.0
Y2014          1580394.0
Y2015          1627508.0
difference       -9933.0
difference2      -9933.0
dtype: float64
               Y2002         Y2003  ...     difference    difference2
mean    1.566034e+06  1.509193e+06  ... -120121.352941 -120121.352941
median  1.584734e+06  1.485909e+06  ...   -9933.000000   -9933.000000

[2 rows x 16 columns]

In [ ]:
income.loc[income.Index == "A",:] #filter

  Index     State    Y2002    Y2003  ...    Y2014    Y2015  difference  difference2
3     A  Arkansas  1485531  1994927  ...  1360959  1329341     -440876      -440876
2     A   Arizona  1742027  1968140  ...  1525866  1647724      198556       198556
1     A    Alaska  1170302  1960378  ...  1580394  1979143      115285       115285
0     A   Alabama  1296530  1317711  ...  1558906  1916661        1056         1056

[4 rows x 18 columns]

In [ ]:
income.loc[income.Index == "A","State"]

3    Arkansas
2     Arizona
1      Alaska
0     Alabama
Name: State, dtype: object

In [ ]:
income.loc[(income.Index == "A") & (income.Y2002 > 1500000),:]

  Index    State    Y2002    Y2003  ...    Y2014    Y2015  difference  difference2
2     A  Arizona  1742027  1968140  ...  1525866  1647724      198556       198556

[1 rows x 18 columns]

In [ ]:
import numpy as np
mydata = {'Crop': ['Rice', 'Wheat', 'Barley', 'Maize'],
        'Yield': [1010, 1025.2, 1404.2, 1251.7],
        'cost' : [102, np.nan, 20, 68]}
crops = pd.DataFrame(mydata)
crops

     Crop   Yield   cost
0    Rice  1010.0  102.0
1   Wheat  1025.2    NaN
2  Barley  1404.2   20.0
3   Maize  1251.7   68.0

#dropna

In [ ]:
print(crops.dropna(how = "any"))
print(crops.dropna(how = "all"))

     Crop   Yield   cost
0    Rice  1010.0  102.0
2  Barley  1404.2   20.0
3   Maize  1251.7   68.0
     Crop   Yield   cost
0    Rice  1010.0  102.0
1   Wheat  1025.2    NaN
2  Barley  1404.2   20.0
3   Maize  1251.7   68.0

In [ ]:
data = pd.DataFrame({"Items" : ["TV","Washing Machine","Mobile","TV","TV","Washing Machine"], "Price" : [10000,50000,20000,10000,10000,40000]})
data

             Items  Price
0               TV  10000
1  Washing Machine  50000
2           Mobile  20000
3               TV  10000
4               TV  10000
5  Washing Machine  40000

In [ ]:
print(data.loc[data.duplicated(),:])
print(data.loc[data.duplicated(keep = "first"),:])

  Items  Price
3    TV  10000
4    TV  10000
  Items  Price
3    TV  10000
4    TV  10000

In [1]:
print(data.loc[data.duplicated(),:])

NameError: ignored

In [ ]:
data.loc[data.duplicated(keep = "last"),:]

  Items  Price
0    TV  10000
3    TV  10000

In [ ]:
data.loc[data.duplicated(keep = False),:]

  Items  Price
0    TV  10000
3    TV  10000
4    TV  10000

In [ ]:
print(data.drop_duplicates(keep = "first"))
print(data.drop_duplicates(keep = "last"))
print(data.drop_duplicates(keep = False,inplace = True))  #by default inplace = False
print(data)
# not needed
# done by unique

             Items  Price
0               TV  10000
1  Washing Machine  50000
2           Mobile  20000
5  Washing Machine  40000
             Items  Price
1  Washing Machine  50000
2           Mobile  20000
4               TV  10000
5  Washing Machine  40000
None
             Items  Price
1  Washing Machine  50000
2           Mobile  20000
5  Washing Machine  40000