In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [3]:
import io
df = pd.read_csv(io.BytesIO(uploaded['titanic.csv']))
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [19]:
df.groupby('Survived').mean()

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [20]:
X = df[['Pclass','Sex','Age','Fare']]
y = df['Survived']

In [21]:
X

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [22]:
from sklearn.preprocessing import LabelEncoder
le_Pclass = LabelEncoder()
le_Sex = LabelEncoder()
le_Age = LabelEncoder()
le_Fare = LabelEncoder()

In [23]:
X['Pclass_n']=le_Pclass.fit_transform(X['Pclass'])
X['Sex_n']=le_Sex.fit_transform(X['Sex'])
X['Age_n']=le_Age.fit_transform(X['Age'])
X['Fare_n']=le_Fare.fit_transform(X['Fare'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [12]:
X

     Pclass     Sex   Age     Fare  Pclass_n  Sex_n  Age_n  Fare_n
0         3    male  22.0   7.2500         2      1     28      18
1         1  female  38.0  71.2833         0      0     51     207
2         3  female  26.0   7.9250         2      0     34      41
3         1  female  35.0  53.1000         0      0     47     189
4         3    male  35.0   8.0500         2      1     47      43
..      ...     ...   ...      ...       ...    ...    ...     ...
886       2    male  27.0  13.0000         1      1     35      85
887       1  female  19.0  30.0000         0      0     24     153
888       3  female   NaN  23.4500         2      0     90     131
889       1    male  26.0  30.0000         0      1     34     153
890       3    male  32.0   7.7500         2      1     42      30

[891 rows x 8 columns]

In [14]:
X.drop(['Pclass','Sex','Age','Fare'],axis='columns',inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [15]:
X

     Pclass_n  Sex_n  Age_n  Fare_n
0           2      1     28      18
1           0      0     51     207
2           2      0     34      41
3           0      0     47     189
4           2      1     47      43
..        ...    ...    ...     ...
886         1      1     35      85
887         0      0     24     153
888         2      0     90     131
889         0      1     34     153
890         2      1     42      30

[891 rows x 4 columns]

In [16]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [17]:
model.fit(X,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
model.score(X,y)

0.9876543209876543